#!/bin/bash
set -e

echo "Cleaning Yum Cache"
yum clean all

echo "Refreshing Yum Cache"
yum makecache

echo "Installing Git"
sudo yum -y groupinstall "Development Tools"
sudo yum -y install gettext-devel openssl-devel perl-CPAN perl-devel zlib-devel
wget https://github.com/git/git/archive/v2.1.2.tar.gz -O git.tar.gz
tar -zxf git.tar.gz
cd git-*
make configure
./configure --prefix=/usr
sudo make install

#echo "Installing python pip"
#yum -y install python-pip

# enable Red Hat Software Collections (SCL) for the latest python and postgresql and more
echo "Enabling Red Hat Software Collections (SCL) repository..."
yum -y -q install centos-release-SCL

echo "Installing Python 3..."
yum -y -q install python33 python33-devel python33-python-virtualenv python33-python-psycopg2

source /opt/rh/python33/enable

wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py

echo "Installing python packages"
pip install virtualenv
pip install pep8

echo "Installing killall command tool"
yum install -y psmisc

echo "Install atom"
wget https://github.com/atom/atom/releases/download/v1.8.0-beta1/atom.x86_64.rpm
yum -y localinstall atom.x86_64.rpm
