#!/bin/bash

echo "Activating python3"
source /opt/rh/python33/enable

echo "Installing nodejs"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
source /home/vagrant/.bashrc
nvm install 5
nvm use 5
nvm alias default 5

echo "Installing supervisor"
npm install -g supervisor
