#!/bin/bash
set -e

echo "Cleaning Yum Cache"
yum clean all

echo "Refreshing Yum Cache"
yum makecache

echo "Installing Git"
sudo yum -y groupinstall "Development Tools"
sudo yum -y install gettext-devel openssl-devel perl-CPAN perl-devel zlib-devel
wget https://github.com/git/git/archive/v2.1.2.tar.gz -O git.tar.gz
tar -zxf git.tar.gz
cd git-*
make configure
./configure --prefix=/usr
sudo make install

# enable Red Hat Software Collections (SCL) for the latest python and postgresql and more
echo "Enabling Red Hat Software Collections (SCL) repository..."
yum -y -q install centos-release-SCL

echo "Installing Python 3..."
yum -y -q install python33 python33-devel python33-python-virtualenv python33-python-psycopg2

source /opt/rh/python33/enable

wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py

echo "Installing python packages"
pip install virtualenv
pip install pep8

echo "Installing killall command tool"
yum install -y psmisc

echo "Install atom"
wget https://github.com/atom/atom/releases/download/v1.8.0-beta1/atom.x86_64.rpm
yum -y localinstall atom.x86_64.rpm

echo "Creating app directory"
mkdir -p applications
sudo chown vagrant applications

if [[ ! -d "vagrant/applications" ]]; then
    git clone git@github.com:Pheonnexx/character_sheets_api.git vagrant/applications

    chown -R chown vagrant /var/applications

    #su - vagrant -c "source /usr/local/bin/virtualenvwrapper.sh && mkvirtualenv some-env && workon some-env && pip install -r /home/$local_user/app/requirements.txt"
fi
